# create data
plants <- c("plant 1", "plant 2", "plant 3", "plant 4", "plant 5")
start_height <- c(10.5, 12.3, 9.8, 11.4, 13.1)  
end_height <- c(12.0, 12.8, 10.1, 12.5, 13.0)   

# data frame
experiment_df <- data.frame(
  plant = plants,
  start_experiment = start_height,
  end_experiment = end_height,
  stringsAsFactors = FALSE
)

# factor
library(tidyr)
experiment_long <- pivot_longer(experiment_df, 
                                cols = c(start_experiment, end_experiment), 
                                names_to = "time", 
                                values_to = "height")
experiment_long$time <- factor(experiment_long$time, levels = c("start_experiment", "end_experiment"))

# Print
experiment_long

# Calculate the percentage growth
growth_percent <- ((end_height - start_height) / start_height) * 100

# Create the 'growth' list
growth_list <- list(
  plant_names = rownames(experiment_df),
  height_change = growth_percent,
  summary_table = data.frame(plants = plants, growth = growth_percent)
)


# Combine into 'my.experiment' list
my.experiment <- list(
  experiment_data = experiment_long,
  growth = growth_list,
)

# list
my.experiment
